version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dadnovin-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YMCMBpass
      POSTGRES_DB: dadnovin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dadnovin-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:YMCMBpass@postgres:5432/dadnovin_db" # production connection string
      NEXTAUTH_SECRET: "supersecret" # use a strong production secret
      # Any other production-specific variables can go here
    depends_on:
      - postgres
    # Remove development volume mounts so the container only uses the built contents

volumes:
  postgres_data:
